---
- name: Clone git repo for volttron root
  ansible.builtin.git:
    repo: "{{ volttron_repo_url }}"
    dest: "{{ volttron_root }}"
    version: "{{ volttron_git_branch }}"
    force: "{{ volttron_git_force_clone }}"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
