---
- name: force python3 for steps to create the venv
  set_fact:
    ansible_python_interpreter: "{{ ansible_python_interpreter }}"

- name: arm-specific ansible venv packages
  pip:
    virtualenv: "{{ venv_for_ansible }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    name:
    - cython
  when: ansible_architecture in ["arm7l"]
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  ## NOTE: on arm-based systems we require cython to be able to install some other dependencies.
  ##       I believe that this is because there are not available binary distributions on PyPI

# Create a dedicated venv to be used by ansible, where dependencies for any
# modules may be installed, leaving both the system, and the volttron venv
# free of those packages
- name: Create ansbile virtual env
  pip:
    virtualenv: "{{ venv_for_ansible }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
    name:
    - pexpect
    - psutil #required for volttron_platform module
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

- name: add selinux to ansible_venv on systems using selinux
  when: ansible_selinux.status == "enabled"
  pip:
    virtualenv: "{{ venv_for_ansible }}"
    name:
    - selinux
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"

# Sets the ansible venv python interpreter to be the one that
# is used for the rest of the tasks.
- name: Set ansible interpreter
  set_fact:
    ansible_python_interpreter: "{{ venv_for_ansible }}/bin/python"
